In [2]:
import numpy as np

In [3]:
# Creation of a simple array
arr_1D = np.array ([1, 2, 3, 4, 5])
print (arr_1D.shape)
print (arr_1D.size)
print (arr_1D)

(5,)
5
[1 2 3 4 5]


In [4]:
# Creation of a 2D array
arr_2D = np.array ([[1, 1, 1],[1, 2, 1], [1,3 ,1]])
print (arr_2D.shape)
print (arr_2D.size)
print (arr_2D)

(3, 3)
9
[[1 1 1]
 [1 2 1]
 [1 3 1]]


In [5]:
# Accessing the array index. Note the diff between a list access
x = arr_2D[1,1]
print (type(x))
print (x)

# Get a row completely
r = arr_2D [1, :]
print (type(r))
print (r)

# Get a column completely
c = arr_2D [:, 1]
print (type(c))
print (c)

<class 'numpy.int64'>
2
<class 'numpy.ndarray'>
[1 2 1]
<class 'numpy.ndarray'>
[1 2 3]


In [6]:
# Create a multi-dimension array with random values
# Its a 6 dimensional array of random numbers, with each dimension length different
arr_mD = np.random.rand (12, 10, 8, 20, 15, 40)

print (arr_mD.shape)
print (arr_mD.size)

# Observe the dimensions ...
print (arr_mD[0,0,0,0,0,:],'\n')
print (arr_mD[0,0,0,0,:,0], '\n')
print (arr_mD[2,3,1,4,4,3:15])

(12, 10, 8, 20, 15, 40)
11520000
[0.47405862 0.10412585 0.55809953 0.57128577 0.66597669 0.68541548
 0.30502459 0.55509803 0.5465015  0.12658623 0.50823167 0.31721349
 0.0435717  0.32061351 0.50570872 0.38829374 0.80236717 0.7407772
 0.00481931 0.75959149 0.67275907 0.83770293 0.31147672 0.58374877
 0.02895931 0.18449615 0.52417116 0.19073682 0.87361814 0.35430799
 0.96780877 0.75387989 0.833152   0.84739545 0.56045519 0.91203576
 0.13212354 0.43384334 0.73007207 0.03058388] 

[0.47405862 0.48200553 0.12338031 0.43725799 0.40689343 0.84540944
 0.80830245 0.38716997 0.49943239 0.93467092 0.93110705 0.86283506
 0.3042002  0.15205162 0.02430143] 

[0.15475974 0.26012029 0.28984685 0.42423136 0.87989829 0.56206753
 0.46692386 0.05778379 0.24695985 0.64142691 0.87911376 0.06242966]


In [11]:
# Want to see complete array ?
print (arr_mD[0,0,0,0,0,:],'\n')
print (arr_mD[0,0,0,0,:,0], '\n')
print (arr_mD[2,3,1,4,4,3])
print (arr_mD[2,3,1,4,4,3:15])


print (arr_mD)

[0.47405862 0.10412585 0.55809953 0.57128577 0.66597669 0.68541548
 0.30502459 0.55509803 0.5465015  0.12658623 0.50823167 0.31721349
 0.0435717  0.32061351 0.50570872 0.38829374 0.80236717 0.7407772
 0.00481931 0.75959149 0.67275907 0.83770293 0.31147672 0.58374877
 0.02895931 0.18449615 0.52417116 0.19073682 0.87361814 0.35430799
 0.96780877 0.75387989 0.833152   0.84739545 0.56045519 0.91203576
 0.13212354 0.43384334 0.73007207 0.03058388] 

[0.47405862 0.48200553 0.12338031 0.43725799 0.40689343 0.84540944
 0.80830245 0.38716997 0.49943239 0.93467092 0.93110705 0.86283506
 0.3042002  0.15205162 0.02430143] 

0.15475973665854137
[0.15475974 0.26012029 0.28984685 0.42423136 0.87989829 0.56206753
 0.46692386 0.05778379 0.24695985 0.64142691 0.87911376 0.06242966]
[[[[[[4.74058616e-01 1.04125848e-01 5.58099531e-01 ... 4.33843338e-01
      7.30072070e-01 3.05838817e-02]
     [4.82005528e-01 4.48078552e-01 7.87136220e-01 ... 9.87916516e-01
      9.46858237e-01 6.69057017e-01]
     [1.233

Since arrays are fixed in size, it cannot be extended on the go like list  
However there are functions provided to add elements to the array  
These functions return a new array

In [12]:
# Appending elements at the end of an existing array
arr_2D = np.array ([[1,1,1], [1,2,1], [1,3,1]])
print (arr_2D)

# Add elements along axis 0 
arr_2D_New = np.append (arr_2D, [[1,4,1]], axis=0)
print (arr_2D_New)

# Add elements along axis 1
arr_2D_New = np.append (arr_2D, [[1],[4],[1]], axis=1)
print (arr_2D_New)

[[1 1 1]
 [1 2 1]
 [1 3 1]]
[[1 1 1]
 [1 2 1]
 [1 3 1]
 [1 4 1]]
[[1 1 1 1]
 [1 2 1 4]
 [1 3 1 1]]


In [13]:
# Concatenate function can be used to merge multiple arrays into one
arr_1 = np.array ([[1,1], [1,2]])
arr_2 = np.array ([[2,1], [2,2]])

print (arr_1, '\n\n', arr_2, '\n\n')

arr_3 = np.concatenate ((arr_1, arr_2), axis=0)
print (arr_3)

[[1 1]
 [1 2]] 

 [[2 1]
 [2 2]] 


[[1 1]
 [1 2]
 [2 1]
 [2 2]]


Array can be re-shaped in terms of dimension & length by reshape method  
The elements are re-arranged to the suit the required dimension, without changing the order  
That means total number of elements will have to match to the dimension and length

In [14]:
# Make an one dimensional array in 2D array
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print (arr.shape)
print (arr)

# Reshape it into 2D
arr_2D = arr.reshape ((3,4))
print (arr_2D.shape)
print (arr_2D)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
# Reshape as 2D but diff length
arr_2D = arr.reshape ((4,3))
print (arr_2D.shape)
print (arr_2D)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
# Reshape as 3D to match the total number of elements
arr_3D = arr.reshape ((2, 2, 3))
print (arr_3D.shape)
print (arr_3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Arithmatic, aggregation, scalar and other mathematical operations can be done using the numpy functions  
Its done in vectorised way, hence faster

In [17]:
# Basic arithmatic operations
arr_1 = np.array ([[1, 2], [3, 4]])
arr_2 = np.array ([[5, 6], [7, 8]])

print ("Addition : \n", arr_1 + arr_2)
print ("Subtraction : \n", arr_1 - arr_2)
print ("Multiplication : \n", arr_1 * arr_2)
print ("Division : \n", arr_1 / arr_2)

Addition : 
 [[ 6  8]
 [10 12]]
Subtraction : 
 [[-4 -4]
 [-4 -4]]
Multiplication : 
 [[ 5 12]
 [21 32]]
Division : 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
# Scalar operations
print ("Scalar Addition : \n", arr_1 + 2)
print ("Scalar Multiplication : \n", arr_1 * 3.54)

Scalar Addition : 
 [[3 4]
 [5 6]]
Scalar Multiplication : 
 [[ 3.54  7.08]
 [10.62 14.16]]


In [19]:
# Aggregation functions can be made on the array
print ("Sum of Array Elements : \n", np.sum(arr_2))
print ("Mean of Array Elements : \n", np.mean(arr_2))
print ("Min of Array Elements : \n", np.min(arr_2))
print ("Max of Array Elements : \n", np.max(arr_2))

Sum of Array Elements : 
 26
Mean of Array Elements : 
 6.5
Min of Array Elements : 
 5
Max of Array Elements : 
 8


In [20]:
# Other Mathematical operations
print ("Square Root : \n", np.sqrt (arr_2))
print ("Sine value : \n", np.sin (arr_2))

Square Root : 
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Sine value : 
 [[-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]
